import tshirt from '../Utils/images/Sell/products/tshirt.jpg'; // Adjust the path as needed

const rows = [
    {
        id: 1,
        variations: 'Color',
        specifications: 'round neck',
        product: 'Shirt',
        brand: 'Brand A',
        price: '1999',
        discount: '10%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 1',
        category: 'Category 1'
    },
    {
        id: 2,
        variations: 'Size',
        specifications: 'self printed',
        product: 'Jeans',
        brand: 'Brand B',
        price: '2999',
        discount: '15%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 2',
        category: 'Category 2'
    },
    {
        id: 3,
        variations: 'Material',
        specifications: 'cotton',
        product: 'T-shirt',
        brand: 'Brand C',
        price: '1499',
        discount: '5%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 3',
        category: 'Category 3'
    },
    {
        id: 4,
        variations: 'Style',
        specifications: 'polka dots',
        product: 'Dress',
        brand: 'Brand D',
        price: '3999',
        discount: '20%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 4',
        category: 'Category 4'
    },
    {
        id: 5,
        variations: 'Design',
        specifications: 'stripes',
        product: 'Skirt',
        brand: 'Brand E',
        price: '499',
        discount: '8%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 5',
        category: 'Category 5'
    },
    {
        id: 6,
        variations: 'Fit',
        specifications: 'slim fit',
        product: 'Pants',
        brand: 'Brand F',
        price: '349',
        discount: '12%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 6',
        category: 'Category 6'
    },
    {
        id: 7,
        variations: 'Pattern',
        specifications: 'floral',
        product: 'Blouse',
        brand: 'Brand G',
        price: '2799',
        discount: '10%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 7',
        category: 'Category 7'
    },
    {
        id: 8,
        variations: 'Neckline',
        specifications: 'v-neck',
        product: 'Sweater',
        brand: 'Brand H',
        price: '3299',
        discount: '15%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 8',
        category: 'Category 8'
    },
    {
        id: 9,
        variations: 'Sleeve length',
        specifications: 'short sleeve',
        product: 'Top',
        brand: 'Brand I',
        price: '1799',
        discount: '5%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 9',
        category: 'Category 9'
    },
    {
        id: 10,
        variations: 'Closure',
        specifications: 'zipper',
        product: 'Jacket',
        brand: 'Brand J',
        price: '4999',
        discount: '25%',
        sample: tshirt,
        quantity: 1, 
        model: 'Model 10',
        category: 'Category 10'
    },
];

export default rows;
